load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")

cc_library(
    name = "aabb3",
    hdrs = ["aabb3.h"],
    srcs = ["aabb3.cc"],
    deps = [
        "//math:vector3d",
        "//math:matrix_4x3",
    ],
)
